{{- if .Values.services.generate.enabled }}

{{- $deployment := include "service.name" (dict "release" $.Release "name" "generate") -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $deployment }}
    xarta-environment: {{ .Release.Name }}
  name: {{ $deployment }}
spec:
  replicas: {{ include "deploy.replicas" .Values.services.generate }}
  selector:
    matchLabels:
      app: {{ $deployment }}
  template:
    metadata:
      annotations:
        checksum-postgresql: {{ include (print $.Template.BasePath "/secrets/postgresql.yaml") . | sha256sum }}
      labels:
        app: {{ $deployment }}
        xarta-environment: {{ .Release.Name }}
        {{- if .Values.defaults.loki.enabled }}
        loki: {{ .Values.defaults.loki.tenant }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: {{ .Values.defaults.securityContext.runAsUser }}
        runAsGroup: {{ .Values.defaults.securityContext.runAsGroup }}
        fsGroup: {{ .Values.defaults.securityContext.fsGroup }}

      {{- include "service.constraints" $ | nindent 6 }}

      dnsPolicy: {{ .Values.defaults.dnsPolicy }}
      restartPolicy: {{ .Values.defaults.restartPolicy }}
      {{ include "service.pullSecrets" $ | nindent 6 -}}

      volumes:
      {{- include "temporaryStorage.volume" $ | nindent 6 }}

      containers:

      - image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ include "image" $ }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ $deployment }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.defaults.securityContext.allowPrivilegeEscalation }}
          privileged: {{ .Values.defaults.securityContext.privileged }}
          runAsNonRoot: {{ .Values.defaults.securityContext.runAsNonRoot }}
        args: [
          "services",
          {{ if $.Values.image.debug -}}
          --debug,
          {{- end }}
          "--run", "generate=latest",
          "--run", "generate=v1"
        ]

        volumeMounts:
        {{- include "temporaryStorage.mount" $ | nindent 8 }}

        ports:
        - containerPort: 8000
          protocol: TCP

        env:
        {{- include "telemetry.env" (dict "root" $ "name" "generate") | nindent 8 }}
        {{- include "postgresql.env" $ | nindent 8 }}
        - name: ARCHIVE_SERVICE_ENDPOINT
          value: http://{{ include "service.name" (dict "release" $.Release "name" "archive") }}/api/archive
        - name: ARCHIVE_SERVICE_TIMEOUT
          value: {{ .Values.services.archive.settings.timeout | default 10 | quote }}
        - name: BUNDLE_SERVICE_ENDPOINT
          value: http://{{ include "service.name" (dict "release" $.Release "name" "bundle") }}/api/bundle
        - name: BUNDLE_SERVICE_TIMEOUT
          value: {{ .Values.services.bundle.settings.timeout | default 10 | quote }}
        - name: RENDER_SERVICE_ENDPOINT
          value: http://{{ include "service.name" (dict "release" $.Release "name" "render") }}/api/render
        - name: RENDER_SERVICE_TIMEOUT
          value: {{ .Values.services.render.settings.timeout | default 10 | quote }}
        - name: NATS_SERVERS
          value: {{ .Values.nats.servers | quote }}
        - name: NATS_WORKERS
          value: {{ .Values.services.generate.settings.nats.workers | default 10 | quote }}
        {{- include "temporaryStorage.env" $ | nindent 8 }}

        {{- include "resources" $ | nindent 8 }}
        {{- include "probes" $ | nindent 8 }}

{{- end }}
