{{- with .Values.database.postgresql }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-db-tools-postgresql
data:
  connectionString: {{ required "database.postgresql.connectionString is required" .connectionString | b64enc | quote }}
{{- end }}
---
{{- with .Values.database.archivePostgresql }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-db-tools-archive-postgresql
data:
  connectionString: {{ required "database.archivePostgresql.connectionString is required" .connectionString | b64enc | quote }}
{{- end }}
