{{- if and .Values.defaults.ingress.enabled .Values.services.doccle.enabled .Values.services.doccle.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- include "ingress.defaultAnnotations" $ | indent 4 }}
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
  name: {{ .Release.Name }}-api-doccle
spec:
  ingressClassName: {{ .Values.defaults.ingress.ingressClassName | quote }}
  tls:
  - hosts:
    {{- range $v := .Values.defaults.ingress.hosts }}
    {{- if $v.tls }}
    - {{ $v.dns | quote }}
    {{- end }}
    {{- end }}
    secretName: {{ .Release.Name }}-ingress-tls
  rules:
  {{- range $v := .Values.defaults.ingress.hosts }}
  - host: {{ $v.dns | quote }}
    http:
      paths:
      - path: /api/doccle/receivers
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-service-doccle
            port:
              number: 80
      - path: /api/v1/doccle/receivers
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-service-doccle
            port:
              number: 80
  {{- end }}
{{- end }}
