[core]
	engine = pg
	# plan_file = sqitch.plan
	# top_dir = .
# [engine "pg"]
	# target = db:pg:
	# registry = sqitch
	# client = psql

[user]
	name = Xarta Labs
	email = xarta@peinser.com
[engine "pg"]
	target = db:postgres://dev:dev@postgres/dev
