{{- if .Values.jobs.replayDeadLetters.enabled }}
{{- $job := printf "%s-replay-dead-letters" .Release.Name -}}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $job }}
spec:
  schedule: {{ .Values.jobs.replayDeadLetters.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $job }}
            {{- if .Values.defaults.loki.enabled }}
            loki: {{ .Values.defaults.loki.tenant }}
            {{- end }}
        spec:
          automountServiceAccountToken: false
          securityContext:
            runAsUser: {{ .Values.defaults.securityContext.runAsUser }}
            runAsGroup: {{ .Values.defaults.securityContext.runAsGroup }}
            fsGroup: {{ .Values.defaults.securityContext.fsGroup }}
          dnsPolicy: {{ .Values.defaults.dnsPolicy }}
          restartPolicy: Never
          containers:
          - image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ include "image" $ }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            name: {{ $job }}
            securityContext:
              allowPrivilegeEscalation: {{ .Values.defaults.securityContext.allowPrivilegeEscalation }}
              privileged: {{ .Values.defaults.securityContext.privileged }}
              runAsNonRoot: {{ .Values.defaults.securityContext.runAsNonRoot }}
            command: ["python"]
            args: ["-m", "xarta.bin.jobs", "--run", "replay_dead_letters=latest"]
            env:
            - name: NATS_SERVERS
              value: {{ .Values.nats.servers | quote }}
            - name: DEAD_LETTER_REPLAY_BATCH_SIZE
              value: {{ .Values.jobs.replayDeadLetters.batchSize | quote }}
            - name: DEAD_LETTER_REPLAY_MAX_ATTEMPTS
              value: {{ .Values.jobs.replayDeadLetters.maxAttempts | quote }}

{{- end }}
