{{- if and .Values.services.archive.enabled .Values.services.archive.settings.adapters.config (not .Values.services.archive.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-archive-adapters
data:
  archive.json: {{ .Values.services.archive.settings.adapters.config | toJson | b64enc | quote }}
{{- end }}
