{{- if and .Values.services.archive.enabled .Values.services.archive.settings.storage.config (not .Values.services.archive.settings.storage.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-archive-storage
data:
  archive-storage.json: {{ .Values.services.archive.settings.storage.config | toJson | b64enc | quote }}
{{- end }}
