{{- with .Values.cache.dragonfly }}
{{- if .connectionString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-core-cache
data:
  dragonglyConnectionString: {{ .connectionString | b64enc | quote }}
{{- end }}
{{- end }}
