{{- if and .Values.services.doccle.enabled (not .Values.services.doccle.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-doccle
type: Opaque
data:
  doccle.json: {{ required "services.doccle.settings.config is required" .Values.services.doccle.settings.config | toJson | b64enc | quote }}
  control-plane-token: {{ required "services.doccle.settings.controlPlaneToken is required" .Values.services.doccle.settings.controlPlaneToken | b64enc | quote }}
  {{- if .Values.services.doccle.settings.callbacks.enabled }}
  callback-certificate-fingerprints: {{ required "services.doccle.settings.callbacks.certificateFingerprints is required when callbacks are enabled" .Values.services.doccle.settings.callbacks.certificateFingerprints | b64enc | quote }}
  {{- end }}
{{- end }}
