{{- if and .Values.services.email.enabled (not .Values.services.email.existingSecret) }}
{{- $config := .Values.services.email.settings.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-email
data:
  email.json: {{ required "services.email.settings.config is required" $config | toJson | b64enc | quote }}
{{- end }}
