{{- if and .Values.services.peppol.enabled (not .Values.services.peppol.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-peppol
data:
  peppol.json: {{ required "services.peppol.settings.config is required" .Values.services.peppol.settings.config | toJson | b64enc | quote }}
{{- end }}
