{{- if and .Values.services.postal.enabled (not .Values.services.postal.existingSecret) }}
{{- $settings := .Values.services.postal.settings }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-postal
type: Opaque
data:
  postal-local-stations.json: {{ required "services.postal.settings.stations is required" $settings.stations | toJson | b64enc | quote }}
  postal-local-storage.json: {{ required "services.postal.settings.storage is required" $settings.storage | toJson | b64enc | quote }}
{{- end }}
