{{- if .Values.database.legacyPostgresqlEnabled }}
{{- with .Values.database.postgresql }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-core-postgresql
data:
  user: {{ required "database.postgresql.user is required" .user | b64enc | quote }}
  database: {{ required "database.postgresql.database is required" .database | b64enc | quote }}
  password: {{ required "database.postgresql.password is required" .password | b64enc | quote }}
  host: {{ required "database.postgresql.host is required" .host | b64enc | quote }}
{{- end }}
{{- end }}
