{{- if and .Values.services.search.enabled (not .Values.services.search.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-search
data:
  search.json: {{ required "services.search.settings.config is required" .Values.services.search.settings.config | toJson | b64enc | quote }}
{{- end }}
