{{- if and .Values.services.sftp.enabled (not .Values.services.sftp.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-sftp
data:
  sftp.json: {{ required "services.sftp.settings.config is required" .Values.services.sftp.settings.config | toJson | b64enc | quote }}
  known_hosts: {{ required "services.sftp.settings.knownHosts is required" .Values.services.sftp.settings.knownHosts | b64enc | quote }}
  id_ed25519: {{ required "services.sftp.settings.b64PrivateKey is required" .Values.services.sftp.settings.b64PrivateKey | quote }}
{{- end }}
