{{- with .Values.services.signature.settings.certificates }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-signing-keys
data:
  publicKey: {{ .b64PublicKey | quote }}
  privateKey: {{ .b64PrivateKey | quote }}
  {{- if .b64CertificateChain }}
  certificateChain: {{ .b64CertificateChain | quote }}
  {{- end }}
{{- end }}
