{{- if and .Values.temporaryStorage.config (not .Values.temporaryStorage.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-temporary-storage
data:
  temporary-storage.json: {{ .Values.temporaryStorage.config | toJson | b64enc | quote }}
{{- end }}
