apiVersion: v2
name: db-tools
description: Database tooling & migrations.
type: application
version: 0.0.10-dev
appVersion: 0.0.10-dev
maintainers:
  - name: Peinser BV
    url: https://github.com/peinser
sources:
  - https://github.com/peinser/xarta
